export const ConstsType = {
  SECRET_KEY_LENGTH: 32,
  COMPRESSED_PUBLIC_KEY_SIZE: 33,
  UNCOMPRESSED_PUBLIC_KEY_SIZE: 65,
  ETH_PUBLIC_KEY_SIZE: 64,
  SIGNATURE_SIZE: 64,
  XCHACHA20_NONCE_LENGTH: 24,
  AEAD_TAG_LENGTH: 16,
  PREFIX_COMPRESS_LENGTH: 8,
} as const
